project_name: thermal-uploader
release:
  github:
    owner: TheCacophonyProject
    name: thermal-uploader
  name_template: '{{.Tag}}'
builds:
- goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
  main: .
  ldflags: -s -w -X main.version={{.Version}}
  binary: thermal-uploader

nfpms:
- vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cacophony Developers <coredev@cacophony.org.nz>
  description: Upload thermal video footage to Cacophony Project API server
  license: GPL v3.0
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  files:
    "_release/thermal-uploader.service": "/etc/systemd/system/thermal-uploader.service"
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
